language: ruby
rvm:
- 2.7.0
services: postgresql
bundler_args: "--jobs=2"
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- bundle exec rails db:setup
- bundle exec rspec
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -d"
cache: bundler
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: fGLuCoAgZsc2v8L58cSvbu/9tupmHe4T4MBye8QbhSzKUSETy2GN1MQmTAuULjKhads5NLl+sgl4HWb52fIz1/8gYJ64GwLJy6PwkZFnv3+pYYVIyYyZMZJkkzblFWGuiKbfvwXkyucw1+63ocTJjaOTJqm20HpQ14YUu5eVMiBKWcwwdbB68rm8SbSRd7FlHR5fFCNBc/LDmp41IqOMY2mSpxNNUnQG9mGsb/T5a8h+pl5rc/jk75BwvqXvYuVVRMXpmo8F3IJyfBsVXrmItL8rpiUftJzWTS/+uvvtRKhzJjgANEhgnuHcnCZaIALdbP/YWqTcvHSv1vTytTkpUjXPo8m/o2bA7adW5UL0cQyqt9jOdgwaSUgYaq1QD7NekKuCUQydBAtosz/O10CVG7Wl7c7sr0p/PUXzUnYJgQXMZ3pQqCzQmk2P6oWOeSLn06DWgidWujj55KgxNO87MPZdvBA68MpvwQlrMi0sKQUPFR5BEqNinPSJjH4YXdm5+w8SvfWnUIIT6DJy2tcu5L87rBxPd+XfeATlPJWevnqF2vMzZW0/MACetuzOqlgJ8vQQn7zdMiFMbo7xdDNb72pbNzZ/NXH3MTPl88OfntfY6IO04NYUVLXFbyLKINlQB/UHbWv/zr3asMWkw7Ar3NwHpARGhXywlM8v0P0Lzag=
  app: clone-the-gram
